#!/bin/bash

# Firebase Setup Script for ITC Conference Frontend
# This script helps you configure Firebase credentials

set -e

echo "╔═══════════════════════════════════════════════════════════════════════╗"
echo "║           Firebase Configuration Setup - ITC India 2026               ║"
echo "╚═══════════════════════════════════════════════════════════════════════╝"
echo ""

# Check if .env.local exists
if [ -f ".env.local" ]; then
    echo "✓ .env.local file exists"
    echo ""
    echo "Current configuration:"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    cat .env.local
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    # Check if it has placeholder values
    if grep -q "your-api-key-here" .env.local || grep -q "your-project-id" .env.local; then
        echo "⚠️  Warning: Your .env.local contains placeholder values!"
        echo ""
    else
        echo "✓ Configuration looks valid (no placeholders detected)"
        echo ""
        read -p "Do you want to reconfigure? (y/N): " reconfigure
        if [[ ! $reconfigure =~ ^[Yy]$ ]]; then
            echo "Keeping existing configuration. Exiting..."
            exit 0
        fi
    fi
else
    echo "✗ .env.local file not found"
    echo "Creating from template..."
    cp .env.local.example .env.local
    echo "✓ Created .env.local"
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Getting Firebase Credentials"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "You need to get your Firebase Web App credentials."
echo ""
echo "Steps:"
echo "1. Open: https://console.firebase.google.com/"
echo "2. Select project: itc--2026"
echo "3. Click ⚙️ → Project Settings"
echo "4. Scroll to 'Your apps' section"
echo "5. If no web app exists, click 'Add app' → Web (</>)"
echo "6. Copy the firebaseConfig values"
echo ""
echo "Press Enter when you have the credentials ready..."
read

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Enter Your Firebase Credentials"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Function to read input with default
read_with_default() {
    local prompt="$1"
    local default="$2"
    local value

    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " value
        echo "${value:-$default}"
    else
        read -p "$prompt: " value
        echo "$value"
    fi
}

# Get current values if they exist
CURRENT_API_KEY=$(grep "NEXT_PUBLIC_FIREBASE_API_KEY=" .env.local 2>/dev/null | cut -d'=' -f2)
CURRENT_AUTH_DOMAIN=$(grep "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=" .env.local 2>/dev/null | cut -d'=' -f2)
CURRENT_PROJECT_ID=$(grep "NEXT_PUBLIC_FIREBASE_PROJECT_ID=" .env.local 2>/dev/null | cut -d'=' -f2)
CURRENT_STORAGE_BUCKET=$(grep "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=" .env.local 2>/dev/null | cut -d'=' -f2)
CURRENT_MESSAGING_SENDER_ID=$(grep "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=" .env.local 2>/dev/null | cut -d'=' -f2)
CURRENT_APP_ID=$(grep "NEXT_PUBLIC_FIREBASE_APP_ID=" .env.local 2>/dev/null | cut -d'=' -f2)

# Read values
echo "Enter your Firebase credentials:"
echo ""

API_KEY=$(read_with_default "API Key (starts with AIza)" "$CURRENT_API_KEY")
AUTH_DOMAIN=$(read_with_default "Auth Domain" "${CURRENT_AUTH_DOMAIN:-itc--2026.firebaseapp.com}")
PROJECT_ID=$(read_with_default "Project ID" "${CURRENT_PROJECT_ID:-itc--2026}")
STORAGE_BUCKET=$(read_with_default "Storage Bucket" "${CURRENT_STORAGE_BUCKET:-itc--2026.appspot.com}")
MESSAGING_SENDER_ID=$(read_with_default "Messaging Sender ID" "$CURRENT_MESSAGING_SENDER_ID")
APP_ID=$(read_with_default "App ID (format: 1:xxx:web:xxx)" "$CURRENT_APP_ID")

echo ""
echo "Backend API URL (usually http://localhost:8080):"
API_URL=$(read_with_default "API Base URL" "http://localhost:8080")

# Create .env.local
cat > .env.local << EOF
# Firebase Configuration
# Generated by setup-firebase.sh on $(date)
NEXT_PUBLIC_FIREBASE_API_KEY=$API_KEY
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$AUTH_DOMAIN
NEXT_PUBLIC_FIREBASE_PROJECT_ID=$PROJECT_ID
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$STORAGE_BUCKET
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$MESSAGING_SENDER_ID
NEXT_PUBLIC_FIREBASE_APP_ID=$APP_ID

# Backend API Configuration
NEXT_PUBLIC_API_BASE_URL=$API_URL
EOF

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Configuration Saved"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ Configuration saved to .env.local"
echo ""

# Validate API key format
if [[ ! $API_KEY =~ ^AIza ]]; then
    echo "⚠️  Warning: API key doesn't start with 'AIza' - please verify it's correct"
    echo ""
fi

# Check if placeholders remain
if [[ $API_KEY == *"your-"* ]] || [[ $API_KEY == "" ]]; then
    echo "❌ Error: API key still contains placeholders or is empty!"
    echo "Please run this script again and enter your real Firebase credentials."
    echo ""
    exit 1
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Next Steps"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Enable Google Sign-in in Firebase Console:"
echo "   • Go to Authentication → Sign-in method"
echo "   • Enable Google provider"
echo ""
echo "2. Add localhost to authorized domains:"
echo "   • Go to Authentication → Settings → Authorized domains"
echo "   • Add 'localhost' if not present"
echo ""
echo "3. Start your backend server:"
echo "   cd /home/krxsna/dev/backend-ITC"
echo "   ./server"
echo ""
echo "4. Start your frontend (in a new terminal):"
echo "   npm run dev"
echo ""
echo "5. Test authentication:"
echo "   • Open http://localhost:3000/login"
echo "   • Click 'Continue with Google'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ Setup complete! Your frontend is now configured."
echo ""
